FROM ubuntu:20.04
RUN sudo apt update && sudo apt upgrade -y
RUN sudo apt install gunicorn python3 pip3

WORKDIR /home/managerpal

COPY requirements.txt /home/managerpal/requirements.txt
RUN pip install -r requirements.txt
RUN pip install psycopg2-binary
COPY ./managerpal /home/managerpal

WORKDIR /home/managerpal
# RUN pip install gunicorn

# RUN gunicorn -w 2 appcore/run
CMD gunicorn 

EXPOSE 80